#Code

In [1]:
import numpy as np

arr_2x2 = np.array([[1, 2], [1, 2]])
print(arr_2x2.shape)
arr_3x4 = np.random.rand(3,4)
print(arr_3x4.shape)
arr_zeros = np.zeros(10)
print(arr_zeros)
arr_ones = np.ones(10)
print(arr_ones)

arr_6x3 = np.random.rand(6,3)
arr_6x3_transpose = arr_6x3.transpose()
print(arr_6x3_transpose.shape)

m = 2
p = 3
n = 2

rand_arr_1 = np.random.rand(m, p)
rand_arr_2 = np.random.rand(p, n)
dot_product = np.dot(rand_arr_1, rand_arr_2)
print(dot_product)




(2, 2)
(3, 4)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
(3, 6)
[[0.51293619 0.59052518]
 [0.84488849 1.32466826]]
